# Generated by Django 5.2.4 on 2025-08-27 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_options_blogpost_author_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(default=1, max_length=200, unique=True, verbose_name="URL-адрес"),
            preserve_default=False,
        ),
    ]
