# Generated by Django 5.2.4 on 2025-07-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(max_length=200, verbose_name="Адрес")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("schedule", models.TextField(verbose_name="График работы")),
                (
                    "map_code",
                    models.TextField(blank=True, help_text="HTML-код карты (iframe)", verbose_name="Код карты"),
                ),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
            },
        ),
    ]
