# Generated by Django 5.2.4 on 2025-08-24 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_product_is_published_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "created_at"],
                "permissions": [
                    ("can_unpublish_product", "Может отменять публикацию продукта"),
                    ("can_delete_any_product", "Может удалять любой продукт"),
                    ("can_change_publication_status", "Может изменять статус публикации"),
                ],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
